# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Build Ad-Hoc ipa for pgyer"
  lane :adhoc do
  	gym(scheme: "WalkieTalkie", export_method: "ad-hoc", output_directory: "./build", export_xcargs: "-allowProvisioningUpdates")
	pgyer(api_key: "20a3d1106b802abbd84ec687eedf17eb", 
            user_key: "3fcd8479c8a50cbaf39119d88d887912", 
           # update_description: get_update_description(), 
           # password: "123456", 
           # install_type: "2"
        )
    # add actions here: https://docs.fastlane.tools/actions
  end
end
