source 'git@github.com:CocoaPods/Specs.git'
source 'git@github.com:castbox/GuruSpecs.git'
install!'cocoapods',:deterministic_uuids=>false

platform :ios, '10.0'
use_frameworks!
use_modular_headers!


def core_pods
    pod 'RxSwift', '5.1'
end

def ui_pods
    pod 'SnapKit', '~> 4.2.0'
    pod 'RxCocoa'
    pod 'RxGesture', '3.0.2'
    pod 'UIColor_Hex_Swift', '~> 4.2.0'
end

def firebase_pods
    # Firebase 推送
    pod 'Firebase/Messaging'

    # Firebase Dynamic Links
    pod 'Firebase/DynamicLinks'

    # Firebase Remote Configure
    pod 'Firebase/RemoteConfig'
    
#    # Firebase auth
    pod 'Firebase/Auth'

    # log
    pod 'Firebase/Analytics'
    #, '6.1.0'
    
    # in app messageing
    pod 'Firebase/InAppMessaging'
    
    # in app messageing
    pod 'Firebase/InAppMessagingDisplay'
    
    pod 'Firebase/DynamicLinks'
end

# specify the version numbers in case of Podfile.lock missing
target 'WalkieTalkie' do
    
    # Objective-C Pods
    pod 'MBProgressHUD', '~> 1.0.0'
    pod 'DeviceKit', '~> 4.0'
#    pod 'LYEmptyView'
    ui_pods

#    pod 'Moya'
    pod 'Moya/RxSwift'

#    pod 'Firebase/Crashlytics'
#    pod 'Fabric', '~> 1.10.2'
#    pod 'Crashlytics', '~> 3.14.0'
    pod 'Firebase/Crashlytics'

    firebase_pods

    pod 'Adjust', '4.21.0'
#    pod 'GuruRater', '~> 0.1.0'
#    pod 'GuruQueue', '~> 0.2.1'
#    pod 'GuruExtensions', :git => 'https://github.com/castbox/GuruExtensions.git', :branch => 'master'
    
    # Swift Pods
    pod 'R.swift', '~> 5.0.2'

    # UserDefaults
    pod 'SwiftyUserDefaults', '~> 5.0.0'
    # 键盘控制
    pod 'IQKeyboardManagerSwift', '~> 6.2.0'
    
    # tip view
#    pod 'EasyTipView', '~> 2.0.4'
    
    # RTC (Agora.io)
#    pod 'AgoraRtcEngine_iOS'
    pod 'AgoraAudio_iOS', '3.1.0'
    pod 'AgoraRtm_iOS', '1.4.2'

    pod 'JLRoutes'
    
    pod 'Reveal-SDK', '4',       :configurations => ["Debug"]
    #https://github.com/realm/SwiftLint
    pod 'SwiftLint', '0.31.0',        :configurations => ["Debug"]
    pod 'Bolts',  :git => 'https://github.com/roremeol/Bolts-ObjC.git', :branch => 'master'

    
    #https://github.com/SwifterSwift/SwifterSwift
    # SwifterSwift is a collection of over 500 native Swift extensions, with handy methods, syntactic sugar,
    # and performance improvements for wide range of primitive data types, UIKit and Cocoa classes –over 500 in 1– for iOS, macOS, tvOS, watchOS and Linux.
    #- Integrate SwiftStdlib extensions only:
    pod 'SwifterSwift'
    
    #- Integrate UIKit extensions only:
#    pod 'SwifterSwift'
    
    pod 'mopub-ios-sdk/Core'
#    pod 'MoPub-AdMob-Adapters'
    pod 'MoPub-UnityAds-Adapters', '3.4.8.1'
    #objc
    pod 'MBProgressHUD', '~> 1.0.0'
    
    pod 'CastboxDebuger', '~> 1.3.2'
    
    # pod for iap
    pod 'SwiftyStoreKit'
    pod 'SwiftyJSON'
    pod 'SwiftHash'
    pod 'loady'
    
    pod 'JXCategoryView'
    pod 'JXPagingView/Paging', '2.0.3'
    pod 'JXSegmentedView'
    pod 'MJRefresh', '~> 3.5.0'
    
    pod 'SnapSDK'
    
    #https://github.com/gmarm/BetterSegmentedControl
    pod 'BetterSegmentedControl'
    
    #https://github.com/mxcl/Path.swift
    pod 'Path.swift', '~> 1.0.0'
    
#     pod 'CocoaDebug', :configurations => ['Debug'] #Required
#    pod 'DoraemonKit/Core', '~> 3.0.2'
    pod 'DoraemonKit/Core', '~> 3.0.2', :configurations => ['Debug'] #Required
    #pod 'DoraemonKit/WithGPS', '~> 3.0.2', :configurations => ['Debug'] #可选
#    pod 'DoraemonKit/WithLoad', '~> 3.0.2', :configurations => ['Debug'] #可选
    #pod 'DoraemonKit/WithLogger', '~> 3.0.2', :configurations => ['Debug'] #可选
    #pod 'DoraemonKit/WithDatabase', '~> 3.0.2', :configurations => ['Debug'] #可选
#    pod 'DoraemonKit/WithMLeaksFinder', '~> 3.0.2', :configurations => ['Debug'] #可选
    #pod 'DoraemonKit/WithWeex', '~> 3.0.2', :configurations => ['Debug'] #可选

    pod 'WSFlexibleTouch'
    
    pod 'TikTokOpenSDK', '~> 3.0.2'
    
    pod 'Kingfisher'
    pod 'YYText'
    pod 'GoogleSignIn'
    
    #https://github.com/sberrevoets/SDCAlertView
    pod 'SDCAlertView'
    pod 'SVGAPlayer'

end

#target 'WalkieTalkieWidgetExtension' do
#  pod 'SwiftyUserDefaults'
#  pod 'Moya/RxSwift'
#  pod 'ObjectMapper'
#end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        if target.name == 'RxSwift'
            target.build_configurations.each do |config|
                if config.name == 'Debug'
                    config.build_settings['OTHER_SWIFT_FLAGS'] ||= ['-D', 'TRACE_RESOURCES']
                end
            end
        end
    end
    
    # 消除 Pods 警告： https://stackoverflow.com/questions/46722323/project-pods-turn-on-whole-module-optimization
    installer.pods_project.build_configurations.each do |config|
        if config.name == 'Release'
            config.build_settings['SWIFT_COMPILATION_MODE'] = 'wholemodule'
        end
    end
    
#     installer.pods_project.targets.each do |target|
#       target.build_configurations.each do |config|
# #        config.build_settings['ENABLE_BITCODE'] = 'NO'
#          config.build_settings['ENABLE_BITCODE'] = 'NO'
#       end
#     end
end

install! 'cocoapods', :disable_input_output_paths => true
